/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import manejoarchivos.ArchivosUsuarios;
import manejoarchivos.BDUsuarios;
import manejoarchivos.Archivo;
import manejoarchivos.Usuarios;

/**
 *
 * @author JHAK
 */
public class Registro extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        initComponents();
        setSize(400, 600);
        setResizable(false);
        setTitle("Registro - Cajero Automatico PROTECH");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper= new ImageIcon("src/main/java/images/fondo_login.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        ImageIcon wallpaper_logo= new ImageIcon("src/main/java/images/logo_protech.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(), jLabel_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icono_logo);
        this.repaint();
    }
    
    
    @Override
    public Image getIconImage() {  //CAMBIAR DIRECCION DEL ICONO POR ERROR DE CARPETA DE RECURSOS
    Image retValue = Toolkit.getDefaultToolkit().getImage("D:/Descargas/Joseph/Joseph/NetBeans/CajeroProtech/src/main/java/images/logo_protech.png");
    return retValue;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Logo = new javax.swing.JLabel();
        Derechos_Autor = new javax.swing.JLabel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_Contrasenia = new javax.swing.JLabel();
        jLabel_Saldo = new javax.swing.JLabel();
        jLabel_Moneda = new javax.swing.JLabel();
        jButton_Registrar = new javax.swing.JButton();
        jTextField_Moneda = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_UserName = new javax.swing.JTextField();
        jTextField_Contrasenia = new javax.swing.JTextField();
        jTextField_Saldo = new javax.swing.JTextField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, 100));

        Derechos_Autor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Derechos_Autor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Derechos_Autor.setText("ProTech2024 © ");
        Derechos_Autor.setToolTipText("");
        getContentPane().add(Derechos_Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        jLabel_Titulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel_Titulo.setText("REGISTRAR NUEVO USUARIO");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Nombre.setText("Nombre: ");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel_UserName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_UserName.setText("UserName:");
        getContentPane().add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel_Contrasenia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Contrasenia.setText("Contraseña:");
        getContentPane().add(jLabel_Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel_Saldo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Saldo.setText("Saldo:");
        getContentPane().add(jLabel_Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel_Moneda.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Moneda.setText("Moneda: ");
        getContentPane().add(jLabel_Moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jButton_Registrar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Registrar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registrar.setText("Registrar");
        jButton_Registrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 150, 40));

        jTextField_Moneda.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_Moneda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField_Moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 190, 30));

        jTextField_Nombre.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 190, 30));

        jTextField_UserName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_UserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 190, 30));

        jTextField_Contrasenia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_Contrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField_Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 190, 30));

        jTextField_Saldo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_Saldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField_Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 190, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        String nombre = jTextField_Nombre.getText().trim();
        String Username = jTextField_UserName.getText().trim();
        String Password = jTextField_Contrasenia.getText().trim();
        String Saldo = jTextField_Saldo.getText().trim();
        String Moneda = jTextField_Moneda.getText().trim();

        BDUsuarios bd = new BDUsuarios();
        ArchivosUsuarios u = new ArchivosUsuarios(nombre, Username, Password, Saldo, Moneda);
        if(bd.registrarUsuario(u)){
            JOptionPane.showMessageDialog(null, "Registro exitoso.");
        } else{
            JOptionPane.showMessageDialog(null, "Falla.");
        }
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Derechos_Autor;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JLabel jLabel_Contrasenia;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Moneda;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Saldo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField jTextField_Contrasenia;
    private javax.swing.JTextField jTextField_Moneda;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Saldo;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
